server:
  port: 7002

spring:
  application:
    name: api-gateway
  config:
    import:
    - optional:configserver:http://localhost:7003
  cloud:    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin  
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
                  routes:      - id: employees-management-register
        uri: lb://employees-management
        predicates:        - Path=/registration
        - Method=POST
        filters:        - RemoveRequestHeader=Cookie
        - RewritePath=/register ,/api/auth/signup
        
      - id: employees-management-login
        uri: lb://employees-management        predicates:        - Path=/login
        - Method=POST        filters:        - RemoveRequestHeader=Cookie
        - RewritePath=/login ,/api/auth/signin
        
      - id: employees-management-get
        uri: lb://employees-management
        predicates:
        - Path=/employees/get
        - Method=GET
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/employees/get ,/api/auth/test
        - AuthorizationHeaderFilter
        
      - id: employees-management-get-userById
        uri: lb://employees-management
        predicates:
        - Path=/employees/get/**
        - Method=GET
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/employees/get/(?<segment>.*) ,/api/employees/$\{segment}
        - AuthorizationHeaderFilter
        
      - id: holiday-management-ask
        uri: lb://holiday-management
        predicates:
        - Path=/holidays/ask
        - Method=POST
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/holidays/ask ,/api/holidays/ask
        - AuthorizationHeaderFilter
        
      - id: holiday-management-get-holidayByEmployeeId
        uri: lb://holiday-management
        predicates:
        - Path=/holidays/get/**
        - Method=GET
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/holidays/get/(?<segment>.*) ,/api/holidays/get/$\{segment}
        - AuthorizationHeaderFilter  
        
      - id: holiday-management-getAll
        uri: lb://holiday-management
        predicates:
        - Path=/holidays/all
        - Method=GET
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/holidays/all ,/api/holidays/all
        - AuthorizationHeaderFilter  
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
