server:
  port: ${PORT:0}

spring:
  application:
    name: holiday-management
  devtools:
    restart:
      enabled: true  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hr-system
  config:
    import:
    - optional:configserver:http://localhost:7003
        
logging:
  level:
    '[org.hibernate.SQL]': DEBUG 
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}} 
